### PR TITLE
feat(*): Support for handling panic error 

### PR DESCRIPTION
**Pull request by linhbkhn95**
### Why did we need it?
- Allow users can handle the panic error if they want
Example:
```
func main() {

	srv := asynq.NewServer(
		asynq.RedisClientOpt{
			Addr: redisAddr,
		},
		asynq.Config{
			// Specify how many concurrent workers to use
			Concurrency: 10,
			// Optionally specify multiple queues with different priority.
			Queues: map[string]int{
				"critical": 6,
				"default":  3,
				"low":      1,
			},
			ErrorHandler: asynq.ErrorHandlerFunc(HandleErrorFunc),
		},
	)

	// mux maps a type to a handler
	mux := asynq.NewServeMux()
	mux.HandleFunc(tasks.TypeEmailDelivery, tasks.HandleEmailDeliveryTask)
	mux.Handle(tasks.TypeImageResize, tasks.NewImageProcessor())
	// ...register other handlers...

	if err := srv.Run(mux); err != nil {
		log.Fatalf("could not run server: %v", err)
	}
}

// The ErrorHandlerFunc type is an adapter to allow the use of  ordinary functions as a ErrorHandler.
// If f is a function with the appropriate signature, ErrorHandlerFunc(f) is a ErrorHandler that calls f.
// HandleError calls fn(ctx, task, err)
func HandleErrorFunc(ctx context.Context, task *asynq.Task, err error) {
	if asynq.IsPanicError(err) {
		// Handle panic error here.
	}
}
```
fixed https://github.com/hibiken/asynq/issues/487

### CODE REVIEW

**Comment by imcvampire** [comment]
LGTM! Please review and merge it!

**Comment by hibiken** [comment]
@linhbkhn95 Thank you for opening a PR, and sorry for the delay in response.
I'd like to avoid adding yet another callback in the Config.
I think a better solution is to wrap in a custom error so that users can leverage the ErrorHandler to handle panic.

Please discuss the API in the #487.

**Comment by linhbkhn95** [comment]
@hibiken tks for your suggestion. I updated it.

**Comment by kamikazechaser** [comment]
+1 This would be a useful feature.

**Review by kamikazechaser — APPROVED** [review]
LGTM, I have been using this feature for a few weeks now.

Maybe `github.com/test-go/testify` is an unnecessary dependency because asynq already uses `github.com/google/go-cmp` in other tests so there will be some little inconsistency.

**Comment by kamikazechaser** [comment]
@hibiken We can merge this.

**Comment by linhbkhn95** [comment]
@hibiken I don't know whether u have a concern about this PR?
I really wanna use this feature this root repo instead of my repo

**Comment by kamikazechaser** [comment]
Thanks @linhbkhn95! It will be included in the next release tag.

**Pull request merged**
