### PR TITLE
Revert "feat (add): panic error handling (#491)"

### PR DESCRIPTION
**Pull request by hibiken**
This reverts commit 551b0c7119800e79e0f30f48049d9ab59feaa9b9.

PR was merged without API change approval.

### CODE REVIEW

**Review by kamikazechaser — APPROVED** [review]
+1 We can re-open #487 and discuss the API again.

**Comment by linhbkhn95** [comment]
can you invite me to this discussion?

**Comment by hibiken** [comment]
@linhbkhn95 I'm ok with the change, would you mind creating a PR for adding an entry to CHANGELOG.md so that we can add this to the upcoming release notes?

**Comment by linhbkhn95** [comment]
@hibiken Thanks, Sure let me add it into CHANGLOG.md file

**Pull request closed without merging**
