### PR TITLE
(core mod) pkg: bump go-redis -> v9

### LINKED ISSUE #570: [FEATURE REQUEST] Update Redis GO library to support Redis 7
**Is your feature request related to a problem? Please describe.**
Steps to reproduce

1. Creating a redis cluster with redis 7. [link](https://redis.io/docs/management/scaling/)
2. Following the steps in wiki [link](https://github.com/hibiken/asynq/wiki/Redis-Cluster)
3. Run the enqueue code below.
```
client := asynq.NewClient(asynq.RedisClusterClientOpt{
		Addrs: []string{"localhost:7000", "localhost:7001", "localhost:7002", "localhost:7003", "localhost:7004", "localhost:7005"},
	})
	defer client.Close()

	// ------------------------------------------------------
	// Example 1: Enqueue task to be processed immediately.
	//            Use (*Client).Enqueue method.
	// ------------------------------------------------------

	task, err := tasks.NewEmailDeliveryTask(42, "some:template:id")
	if err != nil {
		log.Fatalf("could not create task: %v", err)
	}
	queues := []string{"q_1", "q_2", "q_3", "q_4"}
	for i := 0; i < 10000; i++ {
		que := queues[i%4]
		info, err := client.Enqueue(task, asynq.Queue(que))
		if err != nil {
			log.Fatalf("could not enqueue task: %v %s", err, que)
		}

		log.Printf("enqueued task: id=%s queue=%s", info.ID, info.Queue)
	}
```

**Describe the solution you'd like**
Seems to be related to the redis/v8 library results in error [link](https://github.com/go-redis/redis#installation)
Upgrading to redis/v9 might solve this?
```
error: SADD failed: got 4 elements in cluster info address, expected 2 or 3
```

**Additional context**
Following the steps above to figure out how to use asynq

### PR DESCRIPTION
**Pull request by kamikazechaser**
This is a replacement PR for #602 and closes #570. It fixes the tests (all tests pass) and removes v8 references form wherever possible.

Modules `tools` and `x` still indirectly reference v8. They should be updated once the main asynq package is bumped. I have also removed replace directives that were initially added to this PR ( only useful for local dev) and which were previously also removed in #392.

### CODE REVIEW

**Comment by ioannidesalex** [comment]
Bump. This is really good to have.

**Comment by trungdlp-wolffun** [comment]
LGTM @kamikazechaser

**Comment by hibiken** [comment]
Thanks for creating this PR. 
Can you investigate why the build is failing? I'll merge after the build passes

**Comment by kamikazechaser** [comment]
For `build` One of the reasons was related to https://github.com/redis/go-redis/pull/2458. I have pushed the fix. Doesn't break on my local which is `1.20.1`.

I'll investigate the `build-tools` one too.

**Comment by kamikazechaser** [comment]
@hibiken Btw since we are not dealing with any secrets in the CI workflow, could we open up permissions to run the workflows without explicit approvals, wdyt?

**Comment by hibiken** [comment]
@kamikazechaser thanks for looking into this.
Looks like the first contributor will always require approvals to run actions (regardless of which option I pick here). Sorry for the inconvenience! 

Screen Shot 2023-04-08 at 3 59 46 AM

**Comment by kamikazechaser** [comment]
Ah ok.

I see the core build is now passing but the `x` and `tools` is not/will not because of how it references the asynq package version. I think because of how x and tools depend on the core module. we need to merge this in (after tests pass), then individually update `tools` and `x`. So for now I have reverted the go-redis updates made to `x` and `tools`.

Finally, we could tag this as v0.26.0 then update x and tools to ref that, then another update to v0.27.0. We then retract v0.26.0 just to be on the safe side with potential side effects of different go-redis across the modules.

**Comment by kamikazechaser** [comment]
@hibiken Waiting for CI run approval 😅.

**Comment by trungdlp-wolffun** [comment]
> Ah ok.
> 
> I see the core build is now passing but the `x` and `tools` is not/will not because of how it references the asynq package version. I think because of how x and tools depend on the core module. we need to merge this in (after tests pass), then individually update `tools` and `x`. So for now I have reverted the go-redis updates made to `x` and `tools`.
> 
> Finally, we could tag this as v0.26.0 then update x and tools to ref that, then another update to v0.27.0. We then retract v0.26.0 just to be on the safe side with potential side effects of different go-redis across the modules.

It time's for update 🥳

**Comment by kamikazechaser** [comment]
@trungdlp-wolffun  Might need to wait for a tagged release first on the core module.

**Comment by trungdlp-wolffun** [comment]
[v0.24.1](https://github.com/hibiken/asynq/releases/tag/v0.24.1) was released @kamikazechaser 🎉

**Pull request merged**
