### PR TITLE
Remove deprecated protobuf package

### LINKED ISSUE #855: [FEATURE REQUEST] https://github.com/golang/protobuf is Depercated
As the docs says:

> It has been superseded by the [google.golang.org/protobuf](https://pkg.go.dev/mod/google.golang.org/protobuf) module, which contains an updated and simplified API, support for protobuf reflection, and many other improvements. We recommend that new code use the google.golang.org/protobuf module.

### PR DESCRIPTION
**Pull request by aradwann**
removing deprecated github.com/golang/protobuf
and applying go fmt
closes #855

### CODE REVIEW

**Comment by mm2175** [comment]
@hibiken Hi, Could you please review this PR and release a new version? I'm currently cleaning up dependencies in my project that uses asynq, and noticed protobuf as a transitive dependency.

**Comment by pior** [comment]
PRs should be narrowly scoped, as it's hard enough to agree on "one" intention/change.

IMHO, applying `go fmt` without adding a CI check is just noise on a PR, and not an actual improvement.

I'm posting this comment, because I agree with the protobuf changes, and I hope we can get this merged 👌

**Comment by kamikazechaser** [comment]
@aradwann If possible, could we only get the protobuf changes in this PR. I'll apply a gofmt before a tagged release in any case (or with a CI).

**Comment by aradwann** [comment]
@kamikazechaser Hi, currently I am busy with other stuff, and idk when I get back to it

**Comment by kamikazechaser** [comment]
Oh ok. I don't have permissions to push to forks. So I may close this and push/attribute any of your changes in a different commit.

**Comment by aradwann** [comment]
closed in favor of https://github.com/hibiken/asynq/pull/942

**Pull request closed without merging**
