### PR TITLE
remove deprecated protobuf ptypes

### PR DESCRIPTION
**Pull request by aradwann**

### CODE REVIEW

**Comment by aradwann** [comment]
@kamikazechaser Hi, I reworked the PR without the extra fmt part

**Review by pior — APPROVED** [review]
LGTM 
We could upgrade protobuf as well? (in place of https://github.com/hibiken/asynq/pull/932)

**Review by pior — APPROVED** [review]
The changes in `internal/proto/asynq.pb.go` look safe 👍

**Comment by pior** [comment]
Ready for #811

**Review by kamikazechaser — APPROVED** [review]
LGTM. Fixes a couple of security issues.

**Pull request merged**
