### PR TITLE
Change UTC timezone to system time

### PR DESCRIPTION
**Pull request by ioannidesalex**
Issue #671

### CODE REVIEW

**Comment by hibiken** [comment]
@ioannidesalex Thanks for the PR. I think we don't want to change the behavior of the server for everyone. I think we should support custom timezone via `Config`.

**Comment by ioannidesalex** [comment]
Personally I always set all my servers to UTC, even though I live at a different timezone. But in my humble opinion, it makes sense to use whatever timezone the server runs at by default.

**Comment by muhfaris** [comment]
I agree with @hibiken 
what if i want to use utc, do i have to change the time in the operating system? @ioannidesalex

**Comment by ioannidesalex** [comment]
Well noted.

**Comment by huiwanggo** [comment]
is there any progress ？

**Comment by xmwilldo** [comment]
is there any progress ？

**Pull request closed without merging**
